<?php

return [
    'your_available_tickets'  => '',
    'personalize_tickets'     => '',
    'personalize_tickets_for' => '',
    'download_ticket'         => '',
    'catering'                => '',
    'no_catering'             => '',
    'tickets'                 => '',
    'seat'                    => '',
    'name'                    => '',
    'no_name_defined'         => '',
    'catering_preferences'    => '',
    'cancel'                  => '',
    'description'             => '',
    'Comments'                => '',
    'CreationDate'            => '',
    'LastModifiedDate'        => '',
    'RecursiveDescription'    => '',
    'SortOrder'               => '',
    'FatherGroupDescription'  => '',
    'CustomerList'            => '',
    'Mytickets'               => '',
    'id'                      => '',
    'hash'                    => '',   
    'name'                    => '',   
    'group'                   => '',   
    'seat'                    => '',
    'catering'                => '',
    'printed'                 => '',  
    'parking'                 => '',
    'printdate'               => '',
    'Download'                => ''
];
